language: python
python:
  - 2.7

before_install:
  - sudo apt-get -y update

install:
  - sudo apt-get install python-pip python-dev build-essential
  - sudo pip install pykwalify

script:
  - pykwalify --data-file tweets.yml --schema-file schema.yaml; done

notifications:
  email: false
